
# isp lib
file += $(MW_LIB)/libawb.so
file += $(MW_LIB)/libae.so
file += $(MW_LIB)/libaf.so
file += $(MW_LIB)/libisp.so
file += $(MW_LIB)/libisp_algo.so
file += $(MW_LIB)/libraw_replay.so
file += $(MW_LIB)/libraw_dump.so
file += $(MW_LIB)/libcvi_bin_isp.so
file += $(MW_LIB)/libcvi_ispd2.so
file += $(TOP_DIR)/isp-tool-daemon/isp_test/libisp_test.so
file += $(MW_LIB)/libteaisp.so

# mw lib
file += $(MW_LIB)/libcvi_bin.so
file += $(MW_LIB)/libsys.so
file += $(MW_LIB)/libvdec.so
file += $(MW_LIB)/libvenc.so
file += $(MW_LIB)/libvi.so
file += $(MW_LIB)/libvpss.so
file += $(MW_LIB)/libvo.so
file += $(MW_LIB)/libhdmitx.so
file += $(MW_LIB)/librgn.so
file += $(MW_LIB)/libgdc.so
file += $(MW_LIB)/libcvi_audio.so
file += $(MW_LIB)/libcvi_ive.so
file += $(MW_LIB)/libcvi_vqe.so
file += $(MW_LIB)/libcvi_VoiceEngine.so
file += $(MW_LIB)/libcvi_RES1.so
file += $(MW_LIB)/libtinyalsa.so
file += $(MW_LIB)/libcvi_ssp.so
file += $(MW_LIB)/libcvi_ssp2.so
file += $(MW_LIB)/libcvi_dnvqe.so
file += $(MW_LIB)/libmisc.so

# misc lib
file += $(MW_LIB)/libsns_full.so
file += $(MW_LIB)/3rd/libini.so
file += $(MW_LIB)/3rd/libsbc.so

# rtsp lib
file += $(CVI_RTSP_PATH)/install/lib/libcvi_rtsp.so
